### ISSUE TITLE
Raw Images and Videos

### ISSUE THREAD

**Issue by yeliudev** [inst-it/inst-it#1]
Hi @wjpoom, many thanks for sharing this great work! It seems that the images and videos in the released dataset and benchmarks are all with set-of-mark prompts. I was wondering whether you could also provide raw images and videos for them. Thank you!

**Comment by wjpoom** [comment]
Hi, thank you for your interest in our work. I will be working on releasing the original images and videos, and I expect to have them ready within a day. :)

**Comment by yeliudev** [comment]
That would be great!

**Comment by wjpoom** [comment]
Hi, @yeliudev. We have updated the Inst-IT Bench, which provides the raw images and videos, you can visit it [here](https://huggingface.co/datasets/Inst-IT/Inst-IT-Bench).
As for the Inst-IT Dataset, we need some time to check it, maybe tomorrow.
I will let you know when it is ready : )

**Comment by yeliudev** [comment]
Many thanks for the update!

**Comment by wjpoom** [comment]
Hi, @yeliudev. The raw images and videos are also added to [Inst-IT-Dataset](https://huggingface.co/datasets/Inst-IT/Inst-IT-Dataset), sorry for the delay.

**Comment by yeliudev** [comment]
Thanks a lot!
